<a href="https://colab.research.google.com/github/mayooreshmoodanwal/Data-Science/blob/main/Lec_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.random.randint(1,90,(5,5))
print(a)
print('Column wise Mean \n',np.mean(a,0))
print('Row wise Mean \n',np.mean(a,1))
b=np.where(a%2==0,-1,a)
print('Replacing even no by -1 \n',b)
print('Column wise Sort \n',np.sort(a,0))
print('Row wise Sort \n',np.sort(a,1))
print('Column wise Sum \n',np.sum(a,0))
print('Row wise Sum \n',np.sum(a,1))
print('Count negetive',np.sum(b<0,1,0))



[[ 7 20  2 46 27]
 [74 80 81 86 38]
 [65 31 22 61 67]
 [52 39 59 36 72]
 [54 55 57 61 38]]
Column wise Mean 
 [50.4 45.  44.2 58.  48.4]
Row wise Mean 
 [20.4 71.8 49.2 51.6 53. ]
Replacing even no by -1 
 [[ 7 -1 -1 -1 27]
 [-1 -1 81 -1 -1]
 [65 31 -1 61 67]
 [-1 39 59 -1 -1]
 [-1 55 57 61 -1]]
Column wise Sort 
 [[ 7 20  2 36 27]
 [52 31 22 46 38]
 [54 39 57 61 38]
 [65 55 59 61 67]
 [74 80 81 86 72]]
Row wise Sort 
 [[ 2  7 20 27 46]
 [38 74 80 81 86]
 [22 31 61 65 67]
 [36 39 52 59 72]
 [38 54 55 57 61]]
Column wise Sum 
 [252 225 221 290 242]
Row wise Sum 
 [102 359 246 258 265]
Count negetive 13


In [ ]:
st=np.random.randint(20,80,(5,5))
print(st)
de=np.random.randint(20,80,(5,5))
print(de)
rs=(st-de)
print(rs)
crs=np.where(rs<0,0,rs)
print(crs)
tot=np.sum(rs,0)
# print(tot)
cot=np.sum(crs,0)
# print(cot)
print(cot-tot)
zs=np.sum(np.where(crs==0,1,0),axis=0)
print(zs)




[[32 57 46 44 76]
 [51 40 74 61 60]
 [72 46 41 76 41]
 [42 38 73 28 47]
 [36 65 72 57 24]]
[[50 62 27 25 37]
 [76 75 36 47 36]
 [58 40 47 42 60]
 [70 22 67 32 74]
 [51 46 65 79 28]]
[[-18  -5  19  19  39]
 [-25 -35  38  14  24]
 [ 14   6  -6  34 -19]
 [-28  16   6  -4 -27]
 [-15  19   7 -22  -4]]
[[ 0  0 19 19 39]
 [ 0  0 38 14 24]
 [14  6  0 34  0]
 [ 0 16  6  0  0]
 [ 0 19  7  0  0]]
[86 40  6 26 50]
[4 2 1 2 3]


In [ ]:
import pandas as pd
file_ = pd.read_csv('./student_data.csv', sep=',')
print(file_)
print(file_.head())
print(file_.tail())


      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7   
1               4          69            5               3   
2              11          60            7               6   
3               8          99            9               8   
4               5          52            8               6   
...           ...         ...          ...             ...   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
0                        10              62      100.00           Placed  
1                         8              56      100.00           Placed  
2                        10   