<a href="https://colab.research.google.com/github/mayooreshmoodanwal/Data-Science/blob/main/Lec_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#what is numpy?
#Numpy is a library that provides array and its function in python to make its
# operations fast

In [4]:
import numpy as np

In [8]:
a = np.array([1,3,9,0,2])
#numpy arrays are also known as vectors
print(a)

[1 3 9 0 2]


In [9]:
np_arr = np.array([3,3,3,3.3,'hello',False])
print(bool(np_arr[-1]))
#string bool me true return karega , infact kuch bhi bool me
#expect 0, False , empty true hi return karega .
a = False
print(bool(a))

True
False


In [15]:
a = np.zeros(3)
print(a)



[0. 0. 0.]


In [16]:
b = np.zeros((3,4))
print(b)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
c = np.zeros((2,3,4))
print(c)

print(type(c[0][0][0]))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.float64'>


In [21]:
#since it prints <class 'numpy.float64'> float data type we can change it by
c = np.zeros((2,3,4),dtype=int)
print(c)

print(type(c[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [22]:
a = np.empty(4,dtype=int)
print(a)

[      872219973               0 133939989979952 133940892201056]


In [36]:
a = np.ones((2,3,4),dtype=int)
print(a)
print(a.size)
print(a.shape)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
24
(2, 3, 4)


In [24]:
a = np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [25]:
a = np.arange(7,17,2)
print(a)

[ 7  8  9 10 11 12 13 14 15 16]


In [32]:
a = np.linspace(1,5,5,dtype=int)
print(a)

[1 2 3 4 5]


In [46]:
a = np.random.randint(1,17,3)
print(a)

[1 5 6]


In [52]:
a = np.random.choice(6,7)
print(a)

[5 1 2 1 3 3 0]


In [64]:
b = np.array([1,2,3,4])
a = np.array([9,8,7,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)


[10 10 10 10]
[8 6 4 2]
[ 9 16 21 24]
[9.         4.         2.33333333 1.5       ]
[   9   64  343 1296]


In [75]:
a = np.random.randint(1,17,(3,3))
print(a)
b = a.transpose()
print(b)
c = np.concatenate((a,b),axis=0)
print(c)
d = np.concatenate((a,b),axis=1)
print(d)

[[ 3 15 10]
 [ 8 13 10]
 [ 7  4 13]]
[[ 3  8  7]
 [15 13  4]
 [10 10 13]]
[[ 3 15 10]
 [ 8 13 10]
 [ 7  4 13]
 [ 3  8  7]
 [15 13  4]
 [10 10 13]]
[[ 3 15 10  3  8  7]
 [ 8 13 10 15 13  4]
 [ 7  4 13 10 10 13]]


In [78]:
a = np.random.randint(3,17,7)
print(a)
b = np.random.randint(1,19,7)
print(b)
c = np.where(b>a,b,a)
print(c)

[ 9  5 16 16  8 16 14]
[18  8  6 17  5  3 15]
[18  8 16 17  8 16 15]


In [93]:
lst = []
for i in range(7):
    lst.append(int(input()))
a = np.array(lst)
print(a)

print('total run =',np.sum(a))
print('average run =',np.mean(a))
print('max run =',np.max(a),'on day',np.argmax(a) + 1)
print('min run =',np.min(a),'on day',np.argmin(a) + 1)
print('no of centuries =',np.sum(a>=100))
print('no of half centuries =', np.sum((a >= 50) & (a < 100)))
print('no of ducks =',np.sum(a==0))
#


53
103
[ 53 103]
total run = 156
average run = 78.0
max run = 103 on day 2
min run = 53 on day 1
no of centuries = 1
no of half centuries = 1
no of ducks = 0


In [ ]:
import numpy as np

n = int(input("Number of items: "))

prices = []

for i in range(n):
    prices.append(int(input()))

prices = np.array(prices)

print("Prices =", prices)

print("Total Bill    =", np.sum(prices))
print("Average Price =", np.mean(prices))
print("Minimum Price =", np.min(prices))
print("Maximum Price =", np.max(prices))
print("Std Dev       =", np.std(prices))

print("Sorted Prices =", np.sort(prices))
print("Unique Prices =", np.unique(prices))

print("Items > 100   =", prices[np.where(prices > 100)])